#
# Platform configuration for Samsung Exynos 2500 source firmware.
#
# These values describe the source platform only. Device-specific hardware
# contracts remain in target/beyond2lte and must not be copied from the S26 FE.
TARGET_BOARD_API_LEVEL=35

# Dynamic partitions: determined by the target packaging contract.
TARGET_SUPER_GROUP_NAME="none"
TARGET_NONE_SIZE=0
TARGET_SUPER_PARTITION_SIZE=0

# OS
TARGET_OS_SINGLE_SYSTEM_IMAGE="essi"
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false
TARGET_OS_BOOT_DEVICE_PATH="/dev/block/by-name"

# WLAN capability defaults for the source platform. Validate against extracted
# S26 FE vendor blobs before enabling any device-specific behavior.
TARGET_WLAN_CONFIG_CONNECTION_PERSONALIZATION="0"
TARGET_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="100"
TARGET_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="150"
TARGET_WLAN_CONFIG_DYNAMIC_SWITCH="0"
TARGET_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="100"
TARGET_WLAN_SUPPORT_80211AX=true
TARGET_WLAN_SUPPORT_80211AX_6GHZ=true
TARGET_WLAN_SUPPORT_APE_SERVICE=false
TARGET_WLAN_SUPPORT_LOWLATENCY=false
TARGET_WLAN_SUPPORT_MBO=true
TARGET_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
TARGET_WLAN_SUPPORT_MOBILEAP_6G=true
TARGET_WLAN_SUPPORT_MOBILEAP_DUALAP=false
TARGET_WLAN_SUPPORT_MOBILEAP_OWE=false
TARGET_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=false
TARGET_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=false
TARGET_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=true
TARGET_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=true
TARGET_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
TARGET_WLAN_SUPPORT_TWT_CONTROL=false
TARGET_WLAN_SUPPORT_WIFI_TO_CELLULAR=false